application: design-hub-web-716
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /assets/js
  static_dir: assets/js

- url: /assets/css
  static_dir: assets/css

- url: /assets/img
  static_dir: assets/img

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
